### ISSUE TITLE
Typescript

### ISSUE THREAD

**Issue by SeqviriouM** [mistakster/bem-cn-lite#2]
Привет!

Мы активно используем твой проект. Как ты смотришь на то, чтобы перевести его на typescript?

**Comment by mistakster** [comment]
Привет! Я с радостью помогу вам в этом. К сожалению, я сам не пишу на Тайпскрипте и сомневаюсь, что смогу сделать правильные описания типов сам. Готов принять ваш PR и выпустить новую версию как только это будет возможно.

**Comment by SeqviriouM** [comment]
Ок, тогда на днях подготовлю PR

**Comment by mistakster** [comment]
Впустил новую версию https://www.npmjs.com/package/bem-cn-lite/v/4.0.0
